[package]
name = "toucan_ecs"
version = "0.2.0"
description = "Simple and safe ECS library for Rust"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
repository = "https://github.com/toucan-rust/toucan_ecs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["toucan", "ecs", "entity"]
categories = ["data-structures", "game-engines"]
edition = "2021"

[dependencies]
slotmap = "1.0.6"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "basic"
harness = false

[features]
resource = []
